version: '2'

services:
  redis_cache:
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    expose:
      - 6379

  micro-frontend-first-section-fragment:
    container_name: micro-frontend-firstSection-fragment
    build: firstSection-fragment
    links:
      - redis_cache
    networks:
      - local-network
    environment:
      - REDIS_URL=redis://redis_cache
      - NODE_ENV=production
      - PORT=5000
    depends_on:
      - redis_cache

  micro-frontend-beer-of-the-day-fragment:
    container_name: micro-frontend-beerOfTheDay-fragment
    build: beerOfTheDay-fragment
    links:
      - redis_cache
    networks:
      - local-network
    environment:
      - REDIS_URL=redis://redis_cache
      - NODE_ENV=production
      - PORT=5000
    depends_on:
      - redis_cache

  micro-frontend-beer-table-fragment:
    container_name: micro-frontend-beerTable-fragment
    build: beerTable-fragment
    links:
      - redis_cache
    networks:
      - local-network
    environment:
      - REDIS_URL=redis://redis_cache
      - NODE_ENV=production
      - PORT=5000
    depends_on:
      - redis_cache
  
  micro-frontend-home-page:
    container_name: micro-frontend-home-page
    build: home-page
    links:
      - redis_cache
    networks:
      - local-network
    environment:
      - REDIS_URL=redis://redis_cache
      - NODE_ENV=production
      - PORT=5000
    depends_on:
      - redis_cache

  micro-frontend-nginx:
    container_name: micro-frontend-nginx
    build: nginx
    volumes:
      - ./assets:/var/www
    ports:
      - "8888:80"
    networks:
      - local-network
    depends_on:
      - redis_cache
      - micro-frontend-home-page
      - micro-frontend-beer-table-fragment
      - micro-frontend-beer-of-the-day-fragment
      - micro-frontend-first-section-fragment

networks:
  local-network: